---
title: "Testing of multi-modal capabilities"
author: "Saskia Freytag"
date: "04/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(schex)
library(Seurat)
```

## Load data

```{r}
sce <- readRDS("misc/data/cbmc_Filtered_CITEseq.rds")
```

# Make hexbin destination

```{r}
sce <- make_hexbin(sce, nbins=50, dimension_reduction = "umap")
plot_hexbin_density(sce)
```

```{r}
plot_hexbin_feature(sce, mod="ADT", 
                    feature = "MECP2-GAGAAATCAACCAAG", 
                    action="prop_0",
                    type="scale.data")
```

```{r}
plot_hexbin_feature(sce, mod="ADT", 
                    feature = "NeuN-CGGTATATCAACAGA", 
                    action="prop_0",
                    type="scale.data")
```

```{r}
gg <- plot_hexbin_interact(sce, mod=c("RNA", "ADT"),
                     feature = c("Rbfox3", "NeuN-CGGTATATCAACAGA"),
                     interact="corr_spearman",
                     type=c("scale.data", "scale.data"),
                     xlab="umap1",
                     ylab="umap2") +  
  scale_fill_gradient2() + ggtitle("Rbfox3 and NeuN interaction")
  
gg
```

```{r}
ggsave(gg, file="misc/interact.pdf")
```
